version: '3.8'

services:
  app:
    # Usa un'immagine già pubblicata se disponibile, altrimenti costruisci localmente.
    image: ${IMAGE_REGISTRY:-silviosanto6605}/review-manager:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - stack.env
    environment:
      # Override o valori di fallback (non commitare password reali!)
      USER: ${USER:-admin}
      PASSWORD: ${PASSWORD:-changeme}
      PORT: ${PORT:-5000}
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./data:/app/data:rw
      - ./uploads:/app/uploads:rw
    command: sh -c "node createUser.js && node ./bin/www"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${PORT:-5000}/login" ]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
