version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      USER: "myUser"       # Sostituisci con l'username desiderato
      PASSWORD: "myPass"   # Sostituisci con la password desiderata
    command: sh -c "node createUser.js && yarn run start"
    restart: 'unless-stopped'
